### ISSUE TITLE
fix autoflip

### ISSUE THREAD

**Issue by imistyrain** [HectorVilas/solitaire#2]
This project is pretty good, but has a small bug: the card won't be auto flipped when the top card was dragged to another tableau.
just add these codes on line 278 at game.js in function moveCards()
```
  card2flip = fromIndex-1;
  if (card2flip >= 0){
    removeFromHere[card2flip].isFlipped = true;
  }
```

**Comment by HectorVilas** [comment]
Solved: 6113894ecb661e893193e7ebb6a2b71a2573ef74
But I used a little different approach: the last card in the pile will always have it's `isFlipped `property as `true`, to prevent further bugs.
